### PR TITLE
adding database JSON info

### PR DESCRIPTION
**Pull request by chrismellor08**
HERE IS THE DATABASE IN JSON FORMAT YO~

### CODE REVIEW

**Comment by mozecode** [comment]
Hey, the product name is undefined in the table.  The product name needs to be inserted with prodObj.product_name, I think to make it work, but all the rest looks great.  :)

**Comment by chrismellor08** [comment]
Fixed error in product names

**Comment by chrismellor08** [comment]
And another one

**Comment by Rian501** [comment]
Looks good. :+1:

**Pull request merged**
