### PR TITLE
Elcrgm test ticket12

### PR DESCRIPTION
**Pull request by Rian501**
What was changed:
Prompt is fully hooked into the customer creation function which also inputs the customer into DB and returns the new user's ID.
This completes ticket #1.

TO TEST:

1. First do an `npm run db:reset` on the terminal  
2. Then, run `npm start`  
3. Select 1 from main menu.  
4. Input some user information. 
5. See confirmation message, and check your DB browser for full confirmation
6. Also, run `npm test` to ensure the tests are working and passing.

issue  #1

### CODE REVIEW

**Comment by Rian501** [comment]
HOLD.
Discovered a problem in the test suite. Troubleshooting now.

**Comment by Rian501** [comment]
@chrismellor08 and @mozecode, try testing the tests with non-Git-Bash terminals and let us know how it goes.

**Comment by ChrisMellor** [comment]
Hi guys,

Sorry, what is this? I've never seen any of this before?

Thanks,
Christopher Stuart Mellor


^^^^^^^^

HES AN IMPOSTER! DON'T BELIEVE HIS LIES

**Comment by Rian501** [comment]
Sorry man, I @-ed the wrong Chris Mellor!

**Comment by mozecode** [comment]
Pulled it using powershell to try it out in a non GitBash terminal- no difference I can tell.

**Comment by chrismellor08** [comment]
👍  Smashing!

**Pull request merged**
